# CodeRabbit Configuration for StarTune
# See: https://docs.coderabbit.ai/guides/configure-coderabbit

language: "de" # Reviews in German

reviews:
  # Review configuration
  auto_review:
    enabled: true
    drafts: false # Don't review draft PRs

  # What to review
  path_filters:
    - "!**/*.xcodeproj/**"
    - "!**/*.xcworkspace/**"
    - "!**/DerivedData/**"
    - "!**/*.pbxproj"
    - "StarTune/**/*.swift"
    - "*.md"

  # Review settings
  profile: "chill" # Options: assertive, chill, or custom
  request_changes_workflow: false
  high_level_summary: true
  poem: false # No poems in reviews
  review_status: true
  collapse_walkthrough: false

  # Auto-approve simple changes
  auto_approve:
    enabled: false

chat:
  # Allow asking questions in PR comments
  auto_reply: true

# Ignore certain file patterns
ignore:
  - "**/*.xcodeproj/**"
  - "**/*.xcworkspace/**"
  - "**/DerivedData/**"
  - "**/*.pbxuser"
  - "**/*.xcuserdata/**"
  - "**/*.generated.swift"
